version: '3.8'

services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"  # Kong proxy port
      - "8001:8001"  # Kong admin API port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - hospital-network
    
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - SERVER_PORT=9001
    volumes:
      - ./services/user-service:/app
    networks:
      - hospital-network
    
  patient-service:
    build:
      context: .
      dockerfile: services/patient-service/Dockerfile
    ports:
      - "9002:9002"
    environment:
      - SERVER_PORT=9002
    volumes:
      - ./services/patient-service:/app
    networks:
      - hospital-network
    
  appointment-service:
    build:
      context: .
      dockerfile: services/appointment-service/Dockerfile
    ports:
      - "9003:9003"
    environment:
      - SERVER_PORT=9003
    volumes:
      - ./services/appointment-service:/app
    networks:
      - hospital-network
    
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    ports:
      - "9004:9004"
    environment:
      - SERVER_PORT=9004
    volumes:
      - ./services/auth-service:/app
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
