version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=8001
    volumes:
      - ./services/user-service:/app
    # depends_on:
    #   - postgres

  patient-service:
    build:
      context: .
      dockerfile: services/patient-service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SERVER_PORT=8002
    volumes:
      - ./services/patient-service:/app
    # depends_on:
    #   - postgres

  appointment-service:
    build:
      context: .
      dockerfile: services/appointment-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=8003
    volumes:
      - ./services/appointment-service:/app
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=hospital
